### ISSUE TITLE
InvalidIndexError when running scbl-utils to create GEX samplesheet

### ISSUE THREAD

**Issue by mjseignon** [TheJacksonLaboratory/scbl-utils#6]
This is the new error I'm getting after the README table fix. Let me know if you want to see the whole traceback.
Command:
`>scbl-utils samplesheet-from-gdrive /gt/gt_delivery/jax/SingleCellBiology_Group_CT/20240108_23-scbct-154 --outsheet samplesheet-scbct-154.yml`

`InvalidIndexError: (0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
Name: Recipe, dtype: bool, 'Recipe')
`

**Comment by ahmed-said-jax** [comment]
my bad. small error where i was doing `DataFrame[<stuff>]` instead of `DataFrame.loc[<stuff>]`
