### ISSUE TITLE
changing visium reference path

### ISSUE THREAD

**Issue by mjseignon** [TheJacksonLaboratory/scbl-utils#7]
Can we change the visium reference path from 
'/sc/service/pipelines/references/10x-vis'
to
`/sc/service/pipelines/references/10x-rna/`

**Comment by ahmed-said-jax** [comment]
[This commit](https://github.com/TheJacksonLaboratory/scbl-utils/commit/25fd5b17e9c367e40c1ae45a0eaec30cd1a34c57) should take care of this.
